### ISSUE TITLE
Configparser errors

### ISSUE THREAD

**Issue by sriharsha219** [DISHDevEx/leto#31]
1.Getting 'KeyError(key)' to execute the python scripts from this path in the server: /home/ec2-user/leto/
2.When we execute the python script 'reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py' we are getting for 'from .recon_args import parse_recon_args' mentioned in this file:  'utilities/__init__.py'
3. The 'output_prefix_s3' paths in 'config.ini' should be corrected. Some of the mistakes are mentioned below:
a)line 26: add '/' at the end else the file name in the s3 bucket is being appended with 'car'
b)line 37: remove 'test/test/' in the path

**Comment by PierceLovesee** [comment]
Marking this as resolved.  [This PR](https://github.com/DISHDevEx/leto/pull/35/) will address all of these concerns.  Thanks for bringing these up, bhaiya!
