### ISSUE TITLE
Create preprocess and postprocess functionality for Reduction modules to avoid path/folder permission issues

### ISSUE THREAD

**Issue by sriharsha219** [DISHDevEx/leto#36]
Right, now the reduction modules are using the functions in '[auxiliary.py](https://github.com/DISHDevEx/aEye/blob/main/aEye/auxiliary.py)' to create the temporary directories which might create path and permission issues for reading/writing into those directories. 
To avoid this I request to update the reduction modules to use the 'preprocess' and 'postprocess' functions like the way we are doing for reconstruction modules using this file - '[cloud_functionality.py](https://github.com/DISHDevEx/leto/blob/main/utilities/cloud_functionality.py)'
These changes will help us to avoid path/folder permission issues and have more control over the temporary directories

**Comment by vinayakSharm** [comment]
fixed! pull main

**Comment by vinayakSharm** [comment]
https://github.com/DISHDevEx/leto/pull/41
