### ISSUE TITLE
config.ini has wrong mapping between Reduction(R1) and Reconstruction(R2) modules

### ISSUE THREAD

**Issue by sriharsha219** [DISHDevEx/leto#58]
In the 'config.ini' file there is a wrong mapping between Reduction(R1) and Reconstruction(R2) modules.
Example: As per the details mentioned in the 'README.md' file, the 'fastsrgan' should be getting input from 'ffmpeg_resolution_downsampler' but right now it is mapped to 'fps_bitrate'. 
So I request the developer to cross-check the mappings between the R1 and R2 modules and make necessary changes in the 'config.ini' file accordingly.

**Comment by PierceLovesee** [comment]
Resolved in [PR 59](https://github.com/DISHDevEx/leto/pull/59)!  Thanks for documenting this!
